databases:
  - name: url_shortener
    databaseName: url_shortener
    user: url_shortener

services:
  - type: web
    name: url_shortener
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: url_shortener
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
